const Report = require('../models/Report');
const User = require('../models/User');
const ApiError = require('../utils/ApiError');
const asyncHandler = require('../utils/asyncHandler');
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const reportsDir = path.join(__dirname, '..', 'uploads', 'reports');
if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
}

// POST /api/reports/generate
exports.generateReport = asyncHandler(async (req, res) => {
    const { type = 'monthly', startDate, endDate, propertyIndex = 0 } = req.body;
    const user = await User.findById(req.user._id);

    const now = new Date();
    const start = startDate ? new Date(startDate) : new Date(now.getFullYear(), now.getMonth() - 1, 1);
    const end = endDate ? new Date(endDate) : new Date(now.getFullYear(), now.getMonth(), 0);

    const capacity = user.solarSystems[0]?.capacity || 5;
    const annualProduction = capacity * 1400;
    const monthlyProduction = annualProduction / 12;
    const electricityRate = 8;
    const monthlyBill = user.properties[propertyIndex]?.currentEnergyBill || 3000;

    const reportData = {
        energy: {
            totalProduction: +monthlyProduction.toFixed(0),
            totalConsumption: +(monthlyProduction * 0.7).toFixed(0),
            selfConsumption: +(monthlyProduction * 0.7).toFixed(0),
            gridExport: +(monthlyProduction * 0.3).toFixed(0),
        },
        financial: {
            totalSavings: +(monthlyProduction * electricityRate * 0.7).toFixed(0),
            loanPayments: user.financingDetails[0]?.emi || 0,
            netSavings: +(monthlyProduction * electricityRate * 0.7 - (user.financingDetails[0]?.emi || 0)).toFixed(0),
            breakEvenProgress: 35,
        },
        maintenance: {
            cleaningEvents: 1,
            avgEfficiency: 92,
            dustImpact: 4.5,
        },
        environmental: {
            co2Offset: +(monthlyProduction * 0.82 / 1000).toFixed(3),
            treesEquivalent: Math.round(monthlyProduction * 0.82 / 1000 * 45),
        },
    };

    // Generate PDF
    const fileName = `report_${user._id}_${Date.now()}.pdf`;
    const filePath = path.join(reportsDir, fileName);

    const doc = new PDFDocument({ margin: 50 });
    const writeStream = fs.createWriteStream(filePath);
    doc.pipe(writeStream);

    // Header
    doc.fontSize(24).fillColor('#F97316').text('SmartSolar', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(16).fillColor('#333').text('Performance Report', { align: 'center' });
    doc.fontSize(10).fillColor('#666').text(
        `${start.toLocaleDateString()} - ${end.toLocaleDateString()}`,
        { align: 'center' }
    );
    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e5e7eb');
    doc.moveDown(1);

    // User info
    doc.fontSize(12).fillColor('#333').text(`Name: ${user.fullName}`);
    doc.text(`Property: ${user.properties[propertyIndex]?.name || 'Primary'}`);
    doc.text(`System Size: ${capacity} kW`);
    doc.moveDown(1);

    // Energy section
    doc.fontSize(14).fillColor('#F97316').text('⚡ Energy Production');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#333');
    doc.text(`Total Production: ${reportData.energy.totalProduction} kWh`);
    doc.text(`Self Consumption: ${reportData.energy.selfConsumption} kWh`);
    doc.text(`Grid Export: ${reportData.energy.gridExport} kWh`);
    doc.moveDown(1);

    // Financial section
    doc.fontSize(14).fillColor('#F97316').text('💰 Financial Summary');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#333');
    doc.text(`Total Savings: ₹${reportData.financial.totalSavings}`);
    doc.text(`Net Savings: ₹${reportData.financial.netSavings}`);
    doc.text(`Break-even Progress: ${reportData.financial.breakEvenProgress}%`);
    doc.moveDown(1);

    // Environmental section
    doc.fontSize(14).fillColor('#F97316').text('🌍 Environmental Impact');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#333');
    doc.text(`CO₂ Offset: ${reportData.environmental.co2Offset} tons`);
    doc.text(`Equivalent Trees Planted: ${reportData.environmental.treesEquivalent}`);
    doc.moveDown(1);

    // Maintenance section
    doc.fontSize(14).fillColor('#F97316').text('🔧 Maintenance');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#333');
    doc.text(`Average Efficiency: ${reportData.maintenance.avgEfficiency}%`);
    doc.text(`Dust Impact: ${reportData.maintenance.dustImpact}% loss`);
    doc.text(`Cleaning Events: ${reportData.maintenance.cleaningEvents}`);

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#999').text(
        'Generated by SmartSolar — AI-Powered Solar Intelligence Platform',
        { align: 'center' }
    );

    doc.end();

    await new Promise((resolve) => writeStream.on('finish', resolve));

    const report = await Report.create({
        userId: req.user._id,
        propertyIndex,
        title: `${type === 'monthly' ? 'Monthly' : type === 'quarterly' ? 'Quarterly' : 'Annual'} Report - ${start.toLocaleDateString()}`,
        type,
        dateRange: { start, end },
        sections: reportData,
        fileUrl: `/uploads/reports/${fileName}`,
        format: 'pdf',
    });

    res.status(201).json({ success: true, data: { report, downloadUrl: `/api/reports/${report._id}/download` } });
});

// GET /api/reports/list
exports.listReports = asyncHandler(async (req, res) => {
    const reports = await Report.find({ userId: req.user._id }).sort({ generatedAt: -1 }).limit(50);
    res.json({ success: true, data: { reports } });
});

// GET /api/reports/:id/download
exports.downloadReport = asyncHandler(async (req, res) => {
    const report = await Report.findOne({ _id: req.params.id, userId: req.user._id });
    if (!report) throw ApiError.notFound('Report not found');

    const filePath = path.join(__dirname, '..', report.fileUrl);
    if (!fs.existsSync(filePath)) throw ApiError.notFound('Report file not found');

    res.download(filePath, `SmartSolar_Report_${report._id}.pdf`);
});
